/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedCadastrosRouteImport } from './routes/_authenticated/cadastros'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedCongregacoesRouteImport } from './routes/_authenticated/congregacoes'
import { Route as AuthenticatedConsolidadoRouteImport } from './routes/_authenticated/consolidado'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedLicencaRouteImport } from './routes/_authenticated/licenca'
import { Route as AuthenticatedUsuariosRouteImport } from './routes/_authenticated/usuarios'
import { Route as InscricaoEventIdRouteImport } from './routes/inscricao.$eventId'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as AuthenticatedCultosIndexRouteImport } from './routes/_authenticated/cultos.index'
import { Route as AuthenticatedCultosIdRouteImport } from './routes/_authenticated/cultos.$id'
import { Route as AuthenticatedEbdIndexRouteImport } from './routes/_authenticated/ebd.index'
import { Route as AuthenticatedEbdIdRouteImport } from './routes/_authenticated/ebd.$id'
import { Route as AuthenticatedEventosIndexRouteImport } from './routes/_authenticated/eventos.index'
import { Route as AuthenticatedEventosIdRouteImport } from './routes/_authenticated/eventos.$id'
import { Route as AuthenticatedMembrosIndexRouteImport } from './routes/_authenticated/membros.index'
import { Route as AuthenticatedMembrosIdRouteImport } from './routes/_authenticated/membros.$id'
import { Route as AuthenticatedEventosIdControleRouteImport } from './routes/_authenticated/eventos.$id.controle'
import { Route as AuthenticatedEventosIdRelatoriosRouteImport } from './routes/_authenticated/eventos.$id.relatorios'
import { Route as AuthenticatedMembrosIdCarteirinhaRouteImport } from './routes/_authenticated/membros.$id.carteirinha'
import { Route as AuthenticatedMembrosIdCertificadoRouteImport } from './routes/_authenticated/membros.$id.certificado'
import { Route as AuthenticatedEventosIdInscricaoRegIdRouteImport } from './routes/_authenticated/eventos.$id.inscricao.$regId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCadastrosRoute = AuthenticatedCadastrosRouteImport.update({
  id: '/cadastros',
  path: '/cadastros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCongregacoesRoute =
  AuthenticatedCongregacoesRouteImport.update({
    id: '/congregacoes',
    path: '/congregacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsolidadoRoute =
  AuthenticatedConsolidadoRouteImport.update({
    id: '/consolidado',
    path: '/consolidado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLicencaRoute = AuthenticatedLicencaRouteImport.update({
  id: '/licenca',
  path: '/licenca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosRoute = AuthenticatedUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InscricaoEventIdRoute = InscricaoEventIdRouteImport.update({
  id: '/inscricao/$eventId',
  path: '/inscricao/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCultosIndexRoute =
  AuthenticatedCultosIndexRouteImport.update({
    id: '/cultos/',
    path: '/cultos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCultosIdRoute = AuthenticatedCultosIdRouteImport.update({
  id: '/cultos/$id',
  path: '/cultos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbdIndexRoute = AuthenticatedEbdIndexRouteImport.update({
  id: '/ebd/',
  path: '/ebd/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEbdIdRoute = AuthenticatedEbdIdRouteImport.update({
  id: '/ebd/$id',
  path: '/ebd/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosIndexRoute =
  AuthenticatedEventosIndexRouteImport.update({
    id: '/eventos/',
    path: '/eventos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventosIdRoute = AuthenticatedEventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosIndexRoute =
  AuthenticatedMembrosIndexRouteImport.update({
    id: '/membros/',
    path: '/membros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembrosIdRoute = AuthenticatedMembrosIdRouteImport.update({
  id: '/membros/$id',
  path: '/membros/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventosIdControleRoute =
  AuthenticatedEventosIdControleRouteImport.update({
    id: '/controle',
    path: '/controle',
    getParentRoute: () => AuthenticatedEventosIdRoute,
  } as any)
const AuthenticatedEventosIdRelatoriosRoute =
  AuthenticatedEventosIdRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedEventosIdRoute,
  } as any)
const AuthenticatedMembrosIdCarteirinhaRoute =
  AuthenticatedMembrosIdCarteirinhaRouteImport.update({
    id: '/carteirinha',
    path: '/carteirinha',
    getParentRoute: () => AuthenticatedMembrosIdRoute,
  } as any)
const AuthenticatedMembrosIdCertificadoRoute =
  AuthenticatedMembrosIdCertificadoRouteImport.update({
    id: '/certificado',
    path: '/certificado',
    getParentRoute: () => AuthenticatedMembrosIdRoute,
  } as any)
const AuthenticatedEventosIdInscricaoRegIdRoute =
  AuthenticatedEventosIdInscricaoRegIdRouteImport.update({
    id: '/inscricao/$regId',
    path: '/inscricao/$regId',
    getParentRoute: () => AuthenticatedEventosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/consolidado': typeof AuthenticatedConsolidadoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/licenca': typeof AuthenticatedLicencaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/inscricao/$eventId': typeof InscricaoEventIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/': typeof PortalIndexRoute
  '/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/ebd/$id': typeof AuthenticatedEbdIdRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRouteWithChildren
  '/membros/$id': typeof AuthenticatedMembrosIdRouteWithChildren
  '/cultos/': typeof AuthenticatedCultosIndexRoute
  '/ebd/': typeof AuthenticatedEbdIndexRoute
  '/eventos/': typeof AuthenticatedEventosIndexRoute
  '/membros/': typeof AuthenticatedMembrosIndexRoute
  '/eventos/$id/controle': typeof AuthenticatedEventosIdControleRoute
  '/eventos/$id/relatorios': typeof AuthenticatedEventosIdRelatoriosRoute
  '/membros/$id/carteirinha': typeof AuthenticatedMembrosIdCarteirinhaRoute
  '/membros/$id/certificado': typeof AuthenticatedMembrosIdCertificadoRoute
  '/eventos/$id/inscricao/$regId': typeof AuthenticatedEventosIdInscricaoRegIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/cadastros': typeof AuthenticatedCadastrosRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/consolidado': typeof AuthenticatedConsolidadoRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/licenca': typeof AuthenticatedLicencaRoute
  '/usuarios': typeof AuthenticatedUsuariosRoute
  '/inscricao/$eventId': typeof InscricaoEventIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal': typeof PortalIndexRoute
  '/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/ebd/$id': typeof AuthenticatedEbdIdRoute
  '/eventos/$id': typeof AuthenticatedEventosIdRouteWithChildren
  '/membros/$id': typeof AuthenticatedMembrosIdRouteWithChildren
  '/cultos': typeof AuthenticatedCultosIndexRoute
  '/ebd': typeof AuthenticatedEbdIndexRoute
  '/eventos': typeof AuthenticatedEventosIndexRoute
  '/membros': typeof AuthenticatedMembrosIndexRoute
  '/eventos/$id/controle': typeof AuthenticatedEventosIdControleRoute
  '/eventos/$id/relatorios': typeof AuthenticatedEventosIdRelatoriosRoute
  '/membros/$id/carteirinha': typeof AuthenticatedMembrosIdCarteirinhaRoute
  '/membros/$id/certificado': typeof AuthenticatedMembrosIdCertificadoRoute
  '/eventos/$id/inscricao/$regId': typeof AuthenticatedEventosIdInscricaoRegIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/cadastros': typeof AuthenticatedCadastrosRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/congregacoes': typeof AuthenticatedCongregacoesRoute
  '/_authenticated/consolidado': typeof AuthenticatedConsolidadoRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/licenca': typeof AuthenticatedLicencaRoute
  '/_authenticated/usuarios': typeof AuthenticatedUsuariosRoute
  '/inscricao/$eventId': typeof InscricaoEventIdRoute
  '/portal/login': typeof PortalLoginRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/cultos/$id': typeof AuthenticatedCultosIdRoute
  '/_authenticated/ebd/$id': typeof AuthenticatedEbdIdRoute
  '/_authenticated/eventos/$id': typeof AuthenticatedEventosIdRouteWithChildren
  '/_authenticated/membros/$id': typeof AuthenticatedMembrosIdRouteWithChildren
  '/_authenticated/cultos/': typeof AuthenticatedCultosIndexRoute
  '/_authenticated/ebd/': typeof AuthenticatedEbdIndexRoute
  '/_authenticated/eventos/': typeof AuthenticatedEventosIndexRoute
  '/_authenticated/membros/': typeof AuthenticatedMembrosIndexRoute
  '/_authenticated/eventos/$id/controle': typeof AuthenticatedEventosIdControleRoute
  '/_authenticated/eventos/$id/relatorios': typeof AuthenticatedEventosIdRelatoriosRoute
  '/_authenticated/membros/$id/carteirinha': typeof AuthenticatedMembrosIdCarteirinhaRoute
  '/_authenticated/membros/$id/certificado': typeof AuthenticatedMembrosIdCertificadoRoute
  '/_authenticated/eventos/$id/inscricao/$regId': typeof AuthenticatedEventosIdInscricaoRegIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/trocar-senha'
    | '/avisos'
    | '/cadastros'
    | '/checkin'
    | '/congregacoes'
    | '/consolidado'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/licenca'
    | '/usuarios'
    | '/inscricao/$eventId'
    | '/portal/login'
    | '/portal/'
    | '/cultos/$id'
    | '/ebd/$id'
    | '/eventos/$id'
    | '/membros/$id'
    | '/cultos/'
    | '/ebd/'
    | '/eventos/'
    | '/membros/'
    | '/eventos/$id/controle'
    | '/eventos/$id/relatorios'
    | '/membros/$id/carteirinha'
    | '/membros/$id/certificado'
    | '/eventos/$id/inscricao/$regId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/trocar-senha'
    | '/avisos'
    | '/cadastros'
    | '/checkin'
    | '/congregacoes'
    | '/consolidado'
    | '/dashboard'
    | '/documentos'
    | '/financeiro'
    | '/licenca'
    | '/usuarios'
    | '/inscricao/$eventId'
    | '/portal/login'
    | '/portal'
    | '/cultos/$id'
    | '/ebd/$id'
    | '/eventos/$id'
    | '/membros/$id'
    | '/cultos'
    | '/ebd'
    | '/eventos'
    | '/membros'
    | '/eventos/$id/controle'
    | '/eventos/$id/relatorios'
    | '/membros/$id/carteirinha'
    | '/membros/$id/certificado'
    | '/eventos/$id/inscricao/$regId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/trocar-senha'
    | '/_authenticated/avisos'
    | '/_authenticated/cadastros'
    | '/_authenticated/checkin'
    | '/_authenticated/congregacoes'
    | '/_authenticated/consolidado'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentos'
    | '/_authenticated/financeiro'
    | '/_authenticated/licenca'
    | '/_authenticated/usuarios'
    | '/inscricao/$eventId'
    | '/portal/login'
    | '/portal/'
    | '/_authenticated/cultos/$id'
    | '/_authenticated/ebd/$id'
    | '/_authenticated/eventos/$id'
    | '/_authenticated/membros/$id'
    | '/_authenticated/cultos/'
    | '/_authenticated/ebd/'
    | '/_authenticated/eventos/'
    | '/_authenticated/membros/'
    | '/_authenticated/eventos/$id/controle'
    | '/_authenticated/eventos/$id/relatorios'
    | '/_authenticated/membros/$id/carteirinha'
    | '/_authenticated/membros/$id/certificado'
    | '/_authenticated/eventos/$id/inscricao/$regId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  InscricaoEventIdRoute: typeof InscricaoEventIdRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros': {
      id: '/_authenticated/cadastros'
      path: '/cadastros'
      fullPath: '/cadastros'
      preLoaderRoute: typeof AuthenticatedCadastrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/congregacoes': {
      id: '/_authenticated/congregacoes'
      path: '/congregacoes'
      fullPath: '/congregacoes'
      preLoaderRoute: typeof AuthenticatedCongregacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consolidado': {
      id: '/_authenticated/consolidado'
      path: '/consolidado'
      fullPath: '/consolidado'
      preLoaderRoute: typeof AuthenticatedConsolidadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/licenca': {
      id: '/_authenticated/licenca'
      path: '/licenca'
      fullPath: '/licenca'
      preLoaderRoute: typeof AuthenticatedLicencaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios': {
      id: '/_authenticated/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AuthenticatedUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/inscricao/$eventId': {
      id: '/inscricao/$eventId'
      path: '/inscricao/$eventId'
      fullPath: '/inscricao/$eventId'
      preLoaderRoute: typeof InscricaoEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/cultos/': {
      id: '/_authenticated/cultos/'
      path: '/cultos'
      fullPath: '/cultos/'
      preLoaderRoute: typeof AuthenticatedCultosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cultos/$id': {
      id: '/_authenticated/cultos/$id'
      path: '/cultos/$id'
      fullPath: '/cultos/$id'
      preLoaderRoute: typeof AuthenticatedCultosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/': {
      id: '/_authenticated/ebd/'
      path: '/ebd'
      fullPath: '/ebd/'
      preLoaderRoute: typeof AuthenticatedEbdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ebd/$id': {
      id: '/_authenticated/ebd/$id'
      path: '/ebd/$id'
      fullPath: '/ebd/$id'
      preLoaderRoute: typeof AuthenticatedEbdIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/': {
      id: '/_authenticated/eventos/'
      path: '/eventos'
      fullPath: '/eventos/'
      preLoaderRoute: typeof AuthenticatedEventosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$id': {
      id: '/_authenticated/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/eventos/$id'
      preLoaderRoute: typeof AuthenticatedEventosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros/': {
      id: '/_authenticated/membros/'
      path: '/membros'
      fullPath: '/membros/'
      preLoaderRoute: typeof AuthenticatedMembrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros/$id': {
      id: '/_authenticated/membros/$id'
      path: '/membros/$id'
      fullPath: '/membros/$id'
      preLoaderRoute: typeof AuthenticatedMembrosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eventos/$id/controle': {
      id: '/_authenticated/eventos/$id/controle'
      path: '/controle'
      fullPath: '/eventos/$id/controle'
      preLoaderRoute: typeof AuthenticatedEventosIdControleRouteImport
      parentRoute: typeof AuthenticatedEventosIdRoute
    }
    '/_authenticated/eventos/$id/relatorios': {
      id: '/_authenticated/eventos/$id/relatorios'
      path: '/relatorios'
      fullPath: '/eventos/$id/relatorios'
      preLoaderRoute: typeof AuthenticatedEventosIdRelatoriosRouteImport
      parentRoute: typeof AuthenticatedEventosIdRoute
    }
    '/_authenticated/membros/$id/carteirinha': {
      id: '/_authenticated/membros/$id/carteirinha'
      path: '/carteirinha'
      fullPath: '/membros/$id/carteirinha'
      preLoaderRoute: typeof AuthenticatedMembrosIdCarteirinhaRouteImport
      parentRoute: typeof AuthenticatedMembrosIdRoute
    }
    '/_authenticated/membros/$id/certificado': {
      id: '/_authenticated/membros/$id/certificado'
      path: '/certificado'
      fullPath: '/membros/$id/certificado'
      preLoaderRoute: typeof AuthenticatedMembrosIdCertificadoRouteImport
      parentRoute: typeof AuthenticatedMembrosIdRoute
    }
    '/_authenticated/eventos/$id/inscricao/$regId': {
      id: '/_authenticated/eventos/$id/inscricao/$regId'
      path: '/inscricao/$regId'
      fullPath: '/eventos/$id/inscricao/$regId'
      preLoaderRoute: typeof AuthenticatedEventosIdInscricaoRegIdRouteImport
      parentRoute: typeof AuthenticatedEventosIdRoute
    }
  }
}

interface AuthenticatedEventosIdRouteChildren {
  AuthenticatedEventosIdControleRoute: typeof AuthenticatedEventosIdControleRoute
  AuthenticatedEventosIdRelatoriosRoute: typeof AuthenticatedEventosIdRelatoriosRoute
  AuthenticatedEventosIdInscricaoRegIdRoute: typeof AuthenticatedEventosIdInscricaoRegIdRoute
}

const AuthenticatedEventosIdRouteChildren: AuthenticatedEventosIdRouteChildren =
  {
    AuthenticatedEventosIdControleRoute: AuthenticatedEventosIdControleRoute,
    AuthenticatedEventosIdRelatoriosRoute:
      AuthenticatedEventosIdRelatoriosRoute,
    AuthenticatedEventosIdInscricaoRegIdRoute:
      AuthenticatedEventosIdInscricaoRegIdRoute,
  }

const AuthenticatedEventosIdRouteWithChildren =
  AuthenticatedEventosIdRoute._addFileChildren(
    AuthenticatedEventosIdRouteChildren,
  )

interface AuthenticatedMembrosIdRouteChildren {
  AuthenticatedMembrosIdCarteirinhaRoute: typeof AuthenticatedMembrosIdCarteirinhaRoute
  AuthenticatedMembrosIdCertificadoRoute: typeof AuthenticatedMembrosIdCertificadoRoute
}

const AuthenticatedMembrosIdRouteChildren: AuthenticatedMembrosIdRouteChildren =
  {
    AuthenticatedMembrosIdCarteirinhaRoute:
      AuthenticatedMembrosIdCarteirinhaRoute,
    AuthenticatedMembrosIdCertificadoRoute:
      AuthenticatedMembrosIdCertificadoRoute,
  }

const AuthenticatedMembrosIdRouteWithChildren =
  AuthenticatedMembrosIdRoute._addFileChildren(
    AuthenticatedMembrosIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedCadastrosRoute: typeof AuthenticatedCadastrosRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedCongregacoesRoute: typeof AuthenticatedCongregacoesRoute
  AuthenticatedConsolidadoRoute: typeof AuthenticatedConsolidadoRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedLicencaRoute: typeof AuthenticatedLicencaRoute
  AuthenticatedUsuariosRoute: typeof AuthenticatedUsuariosRoute
  AuthenticatedCultosIdRoute: typeof AuthenticatedCultosIdRoute
  AuthenticatedEbdIdRoute: typeof AuthenticatedEbdIdRoute
  AuthenticatedEventosIdRoute: typeof AuthenticatedEventosIdRouteWithChildren
  AuthenticatedMembrosIdRoute: typeof AuthenticatedMembrosIdRouteWithChildren
  AuthenticatedCultosIndexRoute: typeof AuthenticatedCultosIndexRoute
  AuthenticatedEbdIndexRoute: typeof AuthenticatedEbdIndexRoute
  AuthenticatedEventosIndexRoute: typeof AuthenticatedEventosIndexRoute
  AuthenticatedMembrosIndexRoute: typeof AuthenticatedMembrosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedCadastrosRoute: AuthenticatedCadastrosRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedCongregacoesRoute: AuthenticatedCongregacoesRoute,
  AuthenticatedConsolidadoRoute: AuthenticatedConsolidadoRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedLicencaRoute: AuthenticatedLicencaRoute,
  AuthenticatedUsuariosRoute: AuthenticatedUsuariosRoute,
  AuthenticatedCultosIdRoute: AuthenticatedCultosIdRoute,
  AuthenticatedEbdIdRoute: AuthenticatedEbdIdRoute,
  AuthenticatedEventosIdRoute: AuthenticatedEventosIdRouteWithChildren,
  AuthenticatedMembrosIdRoute: AuthenticatedMembrosIdRouteWithChildren,
  AuthenticatedCultosIndexRoute: AuthenticatedCultosIndexRoute,
  AuthenticatedEbdIndexRoute: AuthenticatedEbdIndexRoute,
  AuthenticatedEventosIndexRoute: AuthenticatedEventosIndexRoute,
  AuthenticatedMembrosIndexRoute: AuthenticatedMembrosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  InscricaoEventIdRoute: InscricaoEventIdRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
